# Generated by Django 5.2.3 on 2025-06-23 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='ID must be D### for doctors, R### for admins, or 14-digit for patients.', regex='^((D|R)\\d{3}|\\d{14})$')], verbose_name='National ID'),
        ),
    ]
