# Generated by Django 5.2.3 on 2025-06-23 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brainapp', '0002_remove_user_username_alter_user_national_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
